[package]
name = "server1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive ="1.0"
bincode = "1.3"
ipc-channel = "0.16.0"
lazy_static = "1.4"
ctrlc = "3.2.1" 
sysinfo ="0.26.8"
image = "0.24.5"